name: EternalTags
main: xyz.oribuin.eternaltags.EternalTags
version: '1.0.1'
author: Oribuin
api-version: "1.13"
description: A simple tag plugin alternative to other Tag plugins (With Hex Support)
website: https://oribuin.xyz/
softdepend:
  - PlaceholderAPI