# Configure all the tags you want to use in your server here.
# Here are all the options you can use
# tags:
#  test: # The ID of the tag
#    name: Test # The name of the tag
#    description: # The description of the tag
#     - '&7This is a test tag'
#     - '&7It has multiple lines'
#    permission: # The permission required to use this tag
#    order: 1 # The order of the tag in the GUI
#    icon: # The icon of the tag, Item Names, Lore, Are Overwritten by the tag
#      material: PLAYER_HEAD # The material of the icon
#      texture: You can use a base64 texture here # The texture of the icon, if using HeadDB you can use 'hdb:<id>'
#      glow: true # Whether the icon should glow (You can use a placeholder here too)
#      owner: <username> # The owner of the icon, if using a player head (Set to 'self' to use the player's name)
#      model-data: 1 # The model data of the icon
#      enchantments: # The enchantments of the icon
#       DURABILITY: 1 # The enchantment and level
#      flags: # The item flags of the icon
tags:
  smiley_face:
    name: 'Smiley Face'
    tag: '&f&l<#FFD700^-^&f&l>'
    description:
      - ' '
      - ' &f| &7This tag uses unicode characters'
      - ' &f| &7to display a smiley face in the tag.'
    permission: 'eternaltags.tag.smiley_face'
    order: 0

  heart:
    name: '<3'
    tag: '&f&l<&c&l<3&f&l>'
    description:
      - ' '
      - ' &f| &7This tag uses unicode characters'
      - ' &f| &7to display a heart in the tag.'
      - ' '
    permission: 'eternaltags.tag.heart'
    order: 1
    icon:
      material: 'RED_DYE'
      custom-model-data: 1

  rainbow:
    name: 'Rainbow'
    tag: '&f&l<<r:0.7>&lRainbow&f&l>'
    description:
      - ' '
      - ' &f| &7This tag uses the rainbow color'
      - ' &f| &7to display a rainbow in the tag.'
      - ' '
    permission: 'eternaltags.tag.rainbow'
    order: 2